### PR TITLE
added deployment heroku

### PR DESCRIPTION
**Pull request by juanmaguitar**

### CODE REVIEW

**Comment by juanmaguitar** [comment]
@luisherranz Continuing with the conversation in #9 

---

You are going to kill me but I just realized that Heroku doesn't provide a cache layer: https://devcenter.heroku.com/articles/http-caching

As [the SSR of Frontity is pretty slow](https://community.frontity.org/t/moving-an-existing-wordpress-website-with-over-5000-articles/1477/21) and we always recommend that people should use a cache/CDN, maybe we need to add at least a mention that they should use an external CDN like KeyCDN or Cloudflare.

...

Oh, they have Fastly and Cloudfront as add-ons:
- https://elements.heroku.com/addons/fastly
- https://elements.heroku.com/addons/edge

Maybe we can test them and recommend the best one.

If those services require `cache-control` headers in Frontity let me know. 

---

I'm using this project to do deployment testings https://github.com/frontity-demos/my-frontity-project

This deployment in Heroku → https://salty-dawn-30805.herokuapp.com/
gives this performance report → https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fsalty-dawn-30805.herokuapp.com%2F

Captura de pantalla 2020-04-17 a las 20 51 59

For the add-ons you mention you have to pay. Do we have a company heroku account we can use to make this test?

**Comment by juanmaguitar** [comment]
Performance without plugins (new deploy under team@frontity.com account)

lighthouse-dot-webdotdevsite appspot com__lh_html_url=https%3A%2F%2Fmighty-badlands-59259 herokuapp com%2F(iPad)

**Comment by juanmaguitar** [comment]
Performance after adding Edge plugin

```
⬢  my-frontity-project  master ⦾ heroku addons:create edge:hobby
 ›   Warning: heroku update available from 7.25.0 to 7.39.3.
Creating edge:hobby on ⬢ mighty-badlands-59259... $5/month
Successfully configured https://d19mgjkbf05ovs.cloudfront.net
Created edge-graceful-46203 as EDGE_AWS_ACCESS_KEY_ID, EDGE_AWS_SECRET_ACCESS_KEY, EDGE_DISTRIBUTION_ID, EDGE_URL
Use heroku addons:docs edge to view documentation
```

lighthouse-dot-webdotdevsite appspot com__lh_html_url=https%3A%2F%2Fmighty-badlands-59259 herokuapp com%2F(iPad) (1)

**Comment by juanmaguitar** [comment]
@luisherranz I've added the [Edge](https://elements.heroku.com/addons/edge) plugin to the app https://mighty-badlands-59259.herokuapp.com/ (new deploy) but I don't see any improvement.

Do you think there's some settings I have to do in order to take more advantage of this plugin? Can you help me verify this plugin is a good/bad option?

**Comment by luisherranz** [comment]
Answered in the forum 👍

**Pull request closed without merging**
