### PR TITLE
Add docs for --publicPath in dev & build commands

### PR DESCRIPTION
**Pull request by DAreRodz**
The documentation for this PR: https://github.com/frontity/frontity/pull/420

### CODE REVIEW

**Comment by juanmaguitar** [comment]
Can you explain a bit more what is the use case of using this `--publicPath`. I mean, why this is useful?
Is there any community forum post related to this new feature?

**Comment by DAreRodz** [comment]
There is a Feature Discussions for the `publicPath` option: https://community.frontity.org/t/change-publicpath/1461

It allows to change the path from where you are serving the statics assets i.e. js chunk files, fonts, images, etc.

The public path is included in the generated files by Webpack and cannot be changed after that. In case some people need to change it (because of contrains in their website architecture) they would need an option to do so just before generating the Frontity bundle with `npx frontity build`.

Previously we were hardcoding the public path to `/static/`. Now it is the default value, but you can change it if you want.

**Comment by juanmaguitar** [comment]
@michalczaplinski I think we could explain here → https://docs.frontity.org/deployment
why this option can be important for your project in production
Do you want to start a draft of this explanation here (just throwing some key ideas) ?  I can finish it if you want

**Comment by DAreRodz** [comment]
That would be great, @juanmaguitar. :slightly_smiling_face:

**Comment by michalczaplinski** [comment]
Added a couple paragraphs about why we need the publicPath 🙂

**Comment by DAreRodz** [comment]
@michalczaplinski you requested changes so I re-requested you to review the PR again. If you think it's not necessary you can either approve the changes or remove yourself from reviewers.

I'll merge the PR after that.

**Pull request merged**
