### PR TITLE
Resources Sections to the bottom

### PR DESCRIPTION
**Pull request by juanmaguitar**

### CODE REVIEW

**Comment by mburridge** [comment]
I don't like 'Resources' as a section title, I don't think it describes what is in that section or why it is there.

We need a title that makes clear what the purpose of that section is, i.e. it's to help people new to these technologies.

**Comment by juanmaguitar** [comment]
I've renamed the "Resources" section to "Community Resources" like the React people has → https://reactjs.org/community/support.html

I think is generic and targeted enough so we can add inside more interesting resources for the community

We could add inside for example a "Team" section where we could explain who the DevRel Team are, some key contributors to the code, some key contributors to the community, and so on

**Comment by mburridge** [comment]
Hmm, Community Resources implies a list of links to things that other people have done, which is what the React one is. The JavaScript and React sections aren't really community resources as they've been produced in-house. 

It's a good idea to have a 'Community Resources' section with relevant external links like the React one does, but I'm not sure the JS and React sections belong under it.

**Comment by juanmaguitar** [comment]
@mburridge I think you're right "Community Resources" implies resources done by the Community

In that case, I think just "Resources" is generic enough to include these "Javascript" & "React" sections that are not directly related to the Frontity product

Inside this "Resources" section we also can include some "resources" related to:
- Git & Github → https://github.github.com/training-kit/downloads/github-git-cheat-sheet/ 
- CSS-in-JS as it is an important part of how frontity handles styles
- Isomorphic apps  → as it is what a React Frontity app really is
- Wordpress Custom Fields  → as it is something you can use to really enhance a Frontity site

**Comment by mburridge** [comment]
OK, let's go with "Resources" for now. We can always change it if we think of a better title later on.

I like the idea of adding additional content here such as you suggest in your bullet list. 👍

**Pull request merged**
