### PR TITLE
Add docs for the `useFills` hook

### PR DESCRIPTION
**Pull request by michalczaplinski**
This is the documentation for this PR: https://github.com/frontity/frontity/pull/430

### CODE REVIEW

**Comment by juanmaguitar** [comment]
@michalczaplinski If this a documentation for a feature that is in progress it should be a PR against the `code` branch, so we put there all the documentation contributions and from there we can do the merge to `master` once the release of the features is done

This process is something that is not still documented. Sorry about that.

**Comment by michalczaplinski** [comment]
> @michalczaplinski If this a documentation for a feature that is in progress it should be a PR against the `code` branch, so we put there all the documentation contributions and from there we can do the merge to `master` once the release of the features is done
> 
> This process is something that is not still documented. Sorry about that.

oh, gotcha! I remember that you mentioned this but I thought the branch was gonna be called `dev` and didn't see it so I assumed that you didn't implement process this yet. My bad. Anyways, I've changed the base to `code` as it should be :)

**Comment by michalczaplinski** [comment]
@juanmaguitar I have also ran `npx textlint --fix` on the files that I've added so it looks like it caught some issues that we missed earlier.

**Comment by michalczaplinski** [comment]
I have changed the branch base and added the commits from both `code` and `master` in the process. 

I will close this one and open another PR for the same docs: https://github.com/frontity/gitbook-docs/pull/75

**Pull request closed without merging**
