### PR TITLE
Add docs for `useFills` hook

### PR DESCRIPTION
**Pull request by michalczaplinski**
This is the documentation for this PR: https://github.com/frontity/frontity/pull/430

### CODE REVIEW

**Comment by juanmaguitar** [comment]
@michalczaplinski @luisherranz who is supposed to take care of this PR?

**Comment by luisherranz** [comment]
Me ☝️

But I want to do this before I continue with this https://community.frontity.org/t/code-documentation-workflow/1633/9?u=luisherranz, to see how useful is the markdown generated.

**Comment by luisherranz** [comment]
After discarding the idea of using Typedocs to auto-generate markdown from the TSDocs, I have finished this PR and I think it's ready for review.

**Comment by luisherranz** [comment]
By the way, this is only the API of the `useFills` hook.

We now have to create the `Slot` component. After we do that, we can sit down and see if we need to explain, not only the APIs of the `Slot` and `useFills` tools, but how "Slot and Fills" work in Frontity, add examples in the starter themes and so oy, add examples in the starter themes and so on.

**Comment by luisherranz** [comment]
I've removed the Fills section from the `Roots and Fills` part of the Learning Frontity.

**Comment by luisherranz** [comment]
I've solved the conflicts with the base branch.

**Comment by luisherranz** [comment]
I think it's ready for publishing 👍

**Pull request merged**
