### PR TITLE
Browsers compatibility

### PR DESCRIPTION
**Pull request by juanmaguitar**
https://community.frontity.org/t/ie11-strict-mode-issues-inc-mars-theme/1806

@luisherranz, any other info or explanation that should be added here regarding Frontity compatibility?

### CODE REVIEW

**Comment by mburridge** [comment]
Could this page be called 'Installation Requirements' instead of 'Compatibility'? Then the 'Installation Requirements' and 'Initial Checks' sections on the 'Getting Started' page could be included here along with the new 'Compatibility' section, and then the 'Installation Requirements' section can be linked from the 'Getting Started' page with a note to check installation requirements before proceeding further.

**Comment by juanmaguitar** [comment]
These are different things:
- Installation requirements: Things to be taken into account from the perspective of installing and deploying a Frontity project (server side stuff mostly). → These things can be checked before starting a Frontity project
- Compatibility:Things to be taken into account from the perspective of the final users that are going to view the Frontity project (browsers compatibility, client side stuff mostly) → These things cannot be checked before starting a Frontity project as they depend on the final user

**Comment by luisherranz** [comment]
It's fine @juanmaguitar, thanks for addressing this so quickly 🙂 

I've done a commit with a bit longer explanation and a link to caniuse. But feel free to revert or change it if you think there is unnecessary information.

Also, please check the English grammar is correct.

**Comment by mburridge** [comment]
Reviewed the English usage and made some changes to Luis' text.

**Comment by luisherranz** [comment]
Thanks Michel 🙂

**Pull request merged**
